### ISSUE TITLE
agent.isDestroyed undefined for node 0.12.0 on agentkeepalive@2.x

### ISSUE THREAD

**Issue by matthewmueller** [node-modules/agentkeepalive#14]
Looks like it's defined in `_http_agent.js` but not `agent.js`.

**Comment by fengmk2** [comment]
I need to take a look of changes between 0.11.x and 0.12.0

**Comment by codereflection** [comment]
+1 also running into this issue. Was this due to something changing in node?

**Comment by abarre** [comment]
Does it mean that this agent is not ready for node 0.12.0 ?

**Comment by kevinhikaruevans** [comment]
Doesn't seem to work on v0.12.x, but works just fine on v0.10.40

**Comment by vvo** [comment]
> Does it mean that this agent is not ready for node 0.12.0 ?

@abarre Why not use builtin keepalive agent in node 0.12? Works well

**Comment by abarre** [comment]
@vvo, yes, I see it after posting this comment :)
