### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by vvo** [node-modules/agentkeepalive#22]
Hi, did you already had to handle proxy support using agentkeepalive? How would a user handle proxies while keeping keepalived connections?

**Comment by DesignByOnyx** [comment]
I'm not exactly sure what you are asking here, but I am using this library with [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) and the implementation was seamless:

```javascript
httpProxy.createProxyServer({
    target: {
        host: "127.0.0.1",
        port: "8080"
    },
    agent: new AgentKeepAlive({
        timeout: 60000,
        keepAliveTimeout: 30000
    })
})
```

**Comment by timdp** [comment]
What if I want a _client_ that uses an HTTP proxy _and_ keeps the connection to it alive? Both things require an agent but you can of course only have one agent per request. Also, I'm not sure if it's even possible with HTTPS and CONNECT.

**Comment by loris** [comment]
Any update on this issue? As @timdp said, what we are looking for is a client that can handle both: keep alive agent + proxy agent. Not sure if possible.

**Comment by fengmk2** [comment]
proxy agent is a different feature, keep a package do one thing.

Please use https://www.npmjs.com/package/proxy-agent to support HTTP proxy.

**Comment by 4ext** [comment]
@timdp @loris did anyone of you figure that out? I'm trying to do the same thing and I've been researching this for 20+ hours, it's a real pain.
Thank you!
Also a huge thank you @fengmk2 for this awesome package!

**Comment by timdp** [comment]
Unfortunately not. It'd be good to have a generic way to multiplex agents but I haven't found one. The need for agentkeepalive has somewhat gone away for us though because 1) Node.js has better support for keepalive out of the box and 2) we're exploring fetch-h2 as an HTTP client, which doesn't let you override the agent anyway.

**Comment by zhaojunlike** [comment]
hi bro, so, @4ext @timdp  do You found the solution ?  i need keep-alive http2 proxy lib , I have spent a lot of time to find them
