### ISSUE TITLE
http vs https agents

### ISSUE THREAD

**Issue by defunctzombie** [node-modules/agentkeepalive#26]
Is there a way to just automatically detect using http vs http agent? The issue I was running into was that I used the normal Agent and tried to make https requests. This led to connection resets and socket hangups. Is the normal agent suppose to handle http and https transparently?

**Comment by defunctzombie** [comment]
I am gonna close this until I have something more concrete because I realize that nodejs upstream 0.12 and iojs now have keepalive built in but also use two separate agents. What was happening was that I was using superagent (request would likely have similar issues) and that supports making http or https requests (it resolves the protocol under the hood). However this doesn't play nice with specifying the agent since those are not protocol agnostic.

**Comment by vvo** [comment]
Yes you need different agents as you need different http modules

**Comment by defunctzombie** [comment]
For libraries like request and superagent tho it would be nice to be able
to have a sort of meta-agent.
