### ISSUE TITLE
Auto https.

### ISSUE THREAD

**Issue by DylanPiercey** [node-modules/agentkeepalive#38]
It would be nice if one keep alive agent could automatically switch between http and https requests. I believe it use to work this way but then the api's were separated.

**Comment by fengmk2** [comment]
agentkeepalive API just keep as same as orignal http.Agent, including the usage.

**Comment by DylanPiercey** [comment]
I believe the default http.Agent (in this module) used to work with https as well, is this wrong?

**Comment by fengmk2** [comment]
- http request use `http.Agent`
- https request use `https.Agent` https://nodejs.org/api/https.html#https_class_https_agent

It's hard to detect the going request is http or https.

**Comment by DylanPiercey** [comment]
Alright thanks for pointing this out!
