### ISSUE TITLE
Const Keyword issues with node 0.10

### ISSUE THREAD

**Issue by mohammmo** [node-modules/agentkeepalive#47]
Thank you for your work on this module - I'm not sure if this is something you consider worth fixing but wanted to post it anyway.

We use node 0.10 (I know we need to upgrade and that is in process), but I've run into a minor issue with running agentkeepalive 3.0 in Node 0.10 as that version of node doesn't support the const keyword in strict mode.
But the agentkeepalive package.json still lists node >= 0.10 as dependency. I believe this should be updated so older node 0.10 code doesn't pull the latest version without the Const keyword.

**Comment by fengmk2** [comment]
agentkeepalive 3.x only support node >= 4.0.0, please use agentkeepalive 2.x instead.
