### ISSUE TITLE
An export assignment cannot be used in a module with other exported elements.

### ISSUE THREAD

**Issue by AndrewLeedham** [node-modules/agentkeepalive#73]
![image](https://user-images.githubusercontent.com/5557458/53020821-ad88df80-344f-11e9-9a2f-dbd0e8847d66.png)

`index.d.ts` uses `export = internal`, as well as conventional exports, TS doesn't seem to be happy with this. Perhaps exporting `HttpAgent` as `default` would be more appropriate?

**Comment by AndrewLeedham** [comment]
Seems like this was caused when #70 was merged.

**Comment by fengmk2** [comment]
Please test on 4.0.2

**Comment by AndrewLeedham** [comment]
> Please test on 4.0.2

All working, no TS errors 👍 thanks.
