### ISSUE TITLE
TypeScript import not clear/broken?

### ISSUE THREAD

**Issue by brandonros** [node-modules/agentkeepalive#76]
```
import { default as HttpAgent } from 'agentkeepalive'
import * as HttpAgent from 'agentkeepalive'
import HttpAgent from 'agentkeepalive'
import HttpAgent = require('agentkeepalive')
```

None of these work.

```
> new HttpAgent()
[eval].ts:2
new agentkeepalive_1.default();
^

TypeError: agentkeepalive_1.default is not a constructor
    at [eval].ts:2:1
```

```
Cannot use 'new' with an expression whose type lacks a call or construct signature.

3 new HttpAgent()
```

**Comment by dpoetzschke** [comment]
I am getting the same error on our TypeScript project.
When using the suggested changes to the d.ts and change the import to `* as` TypeScript compiles correctly to `new AgentLeepAlive(this.httpKeepAliveConfig);` instead of the `new AgentLeepAlive.default(this.httpKeepAliveConfig);`

**Comment by sean-krail** [comment]
Hey @fengmk2, just a friendly ping that this issue is blocking our team from using this package with TypeScript.

**Comment by gunzip** [comment]
same here, the proposed patch seems to fix the issue
