### ISSUE TITLE
Support for Node 10 APIs

### ISSUE THREAD

**Issue by AxelTerizaki** [node-modules/agentkeepalive#83]
Judging from [this comment](https://github.com/sindresorhus/got/issues/876#issuecomment-559022705) on got's v10 beta ( sindresorhus/got#876 ), agentkeepalive does not use Node 10's APIs. 

Could it be possible to add that support so we can upgrade to got v10 on our app ?

Thanks in advance.

**Comment by kennethaasan** [comment]
Not sure if this is a problem with _agentkeepalive_. I eventually found out that my issue in https://github.com/sindresorhus/got/issues/876#issuecomment-558622058 is related to using New Relic (https://github.com/newrelic/node-newrelic)

**Comment by AxelTerizaki** [comment]
Oh, I'll have to test it out then, and see what happens, I guess. I'll try to test it this weekend, and if it still works after upgrading to Got 10 then I'll close this issue.

Thanks for the feedback.

**Comment by kennethaasan** [comment]
https://github.com/newrelic/node-newrelic/issues/316

**Comment by AxelTerizaki** [comment]
Seems to work well, so I'm closing it. Sorry for opening it in the first place :)
